### ISSUE TITLE
App crashes when attempting to play videos

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#370]
We found from Google Play Developer Console that the app crashes in some phones while trying to play video.

**Comment by madasamys** [comment]
Observer below error report in play store developer console

```
java.lang.RuntimeException: 
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
  Caused by: android.os.BadParcelableException:
  at android.os.Parcel.readParcelableCreator(Parcel.java:2295)
  at android.os.Parcel.readParcelable(Parcel.java:2245)
 android.support.v4.app.BaseFragmentActivityGingerbread.onCreate(BaseFragmentActivityGingerbread.java:54)
  at android.support.v4.app.FragmentActivity.onCreate(FragmentActivity.java:319)
  at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:85)
  at org.worshipsongs.activity.CustomYoutubeBoxActivity.onCreate(CustomYoutubeBoxActivity.java:76)
  at android.app.Activity.performCreate(Activity.java:5990)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
```

**Comment by madasamys** [comment]
App crashed when play song in Android v4.4.x

**Comment by madasamys** [comment]
[Bad parcelable exception](https://stackoverflow.com/questions/44379747/youtube-android-player-api-throws-badparcelableexception-classnotfoundexception)

**Comment by madasamys** [comment]
This is bug in [Youtube player API](https://issuetracker.google.com/issues/35177191)
