### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by madasamys** [mcruncher/worshipsongs-android#396]
We found from Google Play Developer Console that the app crashes in LAVA phones while trying to changing font size 

Error message 
```
"main" prio=5 tid=1 Runnable
  | group="main" sCount=0 dsCount=0 obj=0x74f06390 self=0xb4e36500
  | sysTid=23508 nice=0 cgrp=default sched=0/0 handle=0xb6fe9c00
  | state=R schedstat=( 0 0 0 ) utm=1343 stm=20 core=1 HZ=100
  | stack=0xbe719000-0xbe71b000 stackSize=8MB
  | held mutexes= "mutator lock"(shared held)
  at org.worshipsongs.preference.FontDialogPreference.onSetInitialValue (FontDialogPreference.java:96)
  at android.preference.Preference.dispatchSetInitialValue (Preference.java:1386)
  at android.preference.Preference.setDefaultValue (Preference.java:1378)
  at org.worshipsongs.preference.FontDialogPreference.onSetInitialValue (FontDialogPreference.java:96)
  at android.preference.Preference.dispatchSetInitialValue (Preference.java:1386)
  at android.preference.Preference.setDefaultValue (Preference.java:1378)
  at org.worshipsongs.preference.FontDialogPreference.onSetInitialValue (FontDialogPreference.java:96)
  at android.preference.Preference.dispatchSetInitialValue (Preference.java:1386)
  at android.preference.Preference.setDefaultValue (Preference.java:1378)
```

**Comment by madasamys** [comment]
Below crash error received from Google developer console

````
java.lang.IndexOutOfBoundsException: 
  at java.util.ArrayList.get(ArrayList.java:411)
  at org.worshipsongs.fragment.SongContentPortraitViewFragment.setActionBarTitle(SongContentPortraitViewFragment.java:523)
  at org.worshipsongs.fragment.SongContentPortraitViewFragment.onResume(SongContentPortraitViewFragment.java:507)
  at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
````
