### ISSUE TITLE
Ensure that the project can be built in Jenkins and the artifacts are published to Play Store

### ISSUE THREAD

**Issue by sskjames** [mcruncher/worshipsongs-android#550]
With recent changes in our build infrastructure, the build is broken. We need to fix it.

**Comment by sibiarunachalam** [comment]
Artifacts repository is updated

**Comment by sibiarunachalam** [comment]
@mcr-paulanand  did SDK and GRADLE  setup in Jenkins

**Comment by sibiarunachalam** [comment]
Cleaned up unnecessary commands in dev pipeline script

**Comment by sibiarunachalam** [comment]
`BUILD SUCCESSFUL in 2m 1s
30 actionable tasks: 30 executed
[Pipeline] }
[Pipeline] // withEnv
Post stage
[Pipeline] archive
The archive step is deprecated, please use archiveArtifacts instead.
[Pipeline] script
[Pipeline] {
[Pipeline] pwd
[Pipeline] readFile
[Pipeline] }
[Pipeline] // script
[Pipeline] androidApkUpload
Cannot upload to Google Play:
- Rollout percentage was not specified; this is now a mandatory parameter
Error when executing success post condition:
hudson.AbortException: Upload to Google Play failed
	at org.jenkinsci.plugins.googleplayandroidpublisher.ApkPublisher.perform(ApkPublisher.java:363)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:99)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:69)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: Upload to Google Play failed
Finished: FAILURE`

**Comment by sibiarunachalam** [comment]
https://issues.jenkins.io/browse/JENKINS-62516
https://github.com/jenkinsci/google-play-android-publisher-plugin#version-40

**Comment by sibiarunachalam** [comment]
RolloutPercentage parameter is included in build command

**Comment by sibiarunachalam** [comment]
Pipeline build has passed in Jenkins
